---
- name: change repo
  block:
    - name: remove old repo
      file:
        path: /etc/yum.repos.d/*.repo
        state: absent
    - name: curl ustack repo
      get_url:
        url: "{{ ustack_repo_url }}"
        dest: /etc/yum.repos.d/
    - name: Install yum-plugin-priorities
      yum:
        name: yum-plugin-priorities
        state: latest
    - name: Install vim
      yum:
        name: vim
        state: latest
    - name: Install tmux
      yum:
        name: tmux
        state: latest
    - name: update   redhat-release
      yum:
        name: redhat-release
        state: latest
      ignore_errors: yes
    - name: check  other repo
      shell: ls /etc/yum.repos.d/CentOS*
      register: result
    - name: remove other repo
      file:
        path: "{{item}}"
        state: absent
      with_items:
         - "{{result.stdout_lines}}"
- name: Install python-tripleoclient
  yum:
    name: python-tripleoclient
    state: latest
- name: Install uos-heat-templates
  yum:
    name: uos-heat-templates
    state: latest
  when: production == 'UOS'
  ignore_errors: yes

- name: Install ustack-tripleo-heat-templates
  yum :
    name: ustack-tripleo-heat-templates
    state: latest
  when: production == 'UDS'
  ignore_errors: yes
