---
- name: add  network config
  block:
    - name: pxe network config
      template:
        src: ifcfg-eth0.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    - name: external network config
      template:
        src: ifcfg-eth1.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-eth1
    - name: restart network
      service:
        name: network
        state: restarted
    - name: ensure network is running
      service:
        name: network
        state: started
    - name: grown disk
      shell:  growpart /dev/vda 1 &&  xfs_growfs /
      become: true
      become_user: root
      ignore_errors: yes
      changed_when: false
